module.exports = {
  array: require('./array'),
  base64: require('./base64'),
  bool: require('./bool'),
  boolOrInteger: require('./boolOrInteger'),
  cidr: require('./cidr'),
  country: require('./country'),
  date: require('./date'),
  email: require('./email'),
  error: require('./error'),
  fileExtension: require('./fileExtension'),
  fqdn: require('./fqdn'),
  gps: require('./gps'),
  ip: require('./ip'),
  iso639: require('./iso639'),
  hashIds: require('./hashIds'),
  hexColor: require('./hexColor'),
  object: require('./object'),
  number: require('./number'),
  ratio: require('./ratio'),
  rgb: require('./rgb'),
  string: require('./string'),
  stringOrInteger: require('./stringOrInteger'),
  url: require('./url'),
  uuid: require('./uuid')
}